Применение SOLID-принципов к redis и es
andrey-lepekhin/Async_API_sprint_2 pull request #15
Opened 2023-01-24 16:54 UTC by Polinavas95

Для редиса не нашла того, что можно поменять
Применила принцип разделения интерфейса в паре мест. Остальные не нашла, мы все хорошо сделали

2023-01-25 13:09 UTC, andrey-lepekhin commented on requirements.txt
> +Django~=3.2  # А нам нужен джанго? Может, удалить?
Давай отсюда выпилим, да!

2023-01-25 13:12 UTC, andrey-lepekhin commented on etl/postgres_to_es/load_data.py
> +def close_es_postgres(es_client, pg_connection):
1. А зачем тут функция, она где-то еще используется?
2. Есть правило, если в функции/классе есть слово "и", значит ее нужно разбить на две :)

2023-01-25 13:12 UTC, andrey-lepekhin commented on etl/postgres_to_es/load_data.py
> +                frequency=int(os.environ.get('TIME_LOOP', 100)),
Может в настройки вынесем константу?

2023-01-25 13:13 UTC, andrey-lepekhin commented on etl/postgres_to_es/settings.py
> +    indexes: list = ['shows', 'genres', 'persons']
Это сломает другие места, которые используют эти настройки.
Навскидку generate_fake_data, может есть и другие

2023-01-25 13:18 UTC, andrey-lepekhin commented on etl/postgres_to_es/settings.py
> +    indexes: list = ['shows', 'genres', 'persons']
Вообще, чтобы такое сделать, это нужен большой рефакторинг, чтобы все классы и функции у нас были полу-универкальными и принимали индекс как настройки. Я бы пока это не трогал, дорого выйдет :)

2023-01-25 13:22 UTC, andrey-lepekhin commented on etl/postgres_to_es/load_data.py
> +    i = 0
Кстати, а где теперь создаются индексы?

2023-01-25 13:23 UTC, andrey-lepekhin requested changes
Очень круто место, чтобы улучшать, но есть вопросики :)

2023-01-25 14:46 UTC, Polinavas95 commented on etl/postgres_to_es/load_data.py
> +def close_es_postgres(es_client, pg_connection):
блин =( ты прав
Для тестов она не нужна будет тоже, я думаю

2023-01-25 14:46 UTC, Polinavas95 commented on etl/postgres_to_es/load_data.py
> +                frequency=int(os.environ.get('TIME_LOOP', 100)),
да, давай

2023-01-25 14:51 UTC, Polinavas95 commented on etl/postgres_to_es/load_data.py
> +def create_indexes(client, index, create_indexes_defs):
хорошо!

2023-01-25 14:54 UTC, Polinavas95 commented on etl/postgres_to_es/load_data.py
> +    i = 0
Хм, видимо, они создавались при запуске метода bulk. Странно, что работало. Вернула создание индексов

2023-01-25 14:56 UTC, Polinavas95 commented on etl/postgres_to_es/settings.py
> +    indexes: list = ['shows', 'genres', 'persons']
я помещу в список переменные из настроек. Могу импортировать в методе
Ты прав, я не проверила все места. Они же по отдельности используются не только при bulk-методе

2023-01-25 14:56 UTC, Polinavas95 commented on requirements.txt
> +Django~=3.2  # А нам нужен джанго? Может, удалить?
окей!

2023-01-25 16:18 UTC, andrey-lepekhin commented on etl/postgres_to_es/settings.py
> +    bulk_size: int
Если сюда добавлять, то нужно и в .env.example тоже, иначе ревьюер будет гадать какие там цифры нужны. Или можно даже не захламлять тот файл, а добавить сюда дефолтные значения

2023-01-26 05:18 UTC, andrey-lepekhin approved these changes

2023-01-26 05:20 UTC, merged