сделала тесты для персон
andrey-lepekhin/Async_API_sprint_2 pull request #17
Opened 2023-01-26 15:53 UTC by Polinavas95

Уменьшила время кэширования (потом надо вернуть)

2023-01-26 16:17 UTC, andrey-lepekhin commented on tests/functional/src/test_cache.py
> +pytestmark = pytest.mark.asyncio
О, а можешь объяснить смысл изменения? Это вместо декоратора? Работает на все тесты в файле?

2023-01-26 16:18 UTC, andrey-lepekhin commented on tests/functional/src/test_cache.py
> +        ('6e429cff-c8a2-4d17-8b12-6532a8a1ac9b', '6e429cff-c8a2-4d17-8b12-6532a8a1ac9b'),
если тут одинаковые значения не очень понятно зачем их дублировать, почему не использовать одно значение?

2023-01-26 16:19 UTC, andrey-lepekhin commented on tests/functional/src/test_cache.py
> +        ('6e429cff-c8a2-4d17-8b12-6532a8a1ac9b', '6e429cff-c8a2-4d17-8b12-6532a8a1ac9b'),
Также не очень понятно зачем тут три проверки, почему одной не будет достаточно?

2023-01-26 16:24 UTC, andrey-lepekhin commented on tests/functional/src/test_cache.py
> +    sleep(70)
Так плохо потому что тест будет прогоняться 70 секунд, это долго.
Нужен механизм, который будет временно уменьшать период кэширования на время теста, а потом восстанавливать.

Или, что проще, -- на тестовый стенд в .env подмешивать низкое количество секунд в настройку кэша

2023-01-26 16:25 UTC, andrey-lepekhin commented on tests/functional/src/test_cache.py
> +    with pytest.raises(KeyError):
Прикольно, не знал про эту конструкцию, спасибо

2023-01-26 16:27 UTC, andrey-lepekhin commented on tests/functional/src/test_cache.py
> +async def test_persons_cache_errors(
Я бы назвал более явно что это про проверку истечения кэша.
Например что-то про cache expiration

2023-01-26 16:28 UTC, andrey-lepekhin commented on tests/functional/src/test_persons.py
> +@pytest.mark.parametrize(
Зачем parametrize, если только один тест-кейс?

2023-01-26 16:30 UTC, andrey-lepekhin commented on tests/functional/src/test_persons.py
> +RANDOM_ELEM = random.randint(0, len(data_persons)-1)
не используется?

2023-01-26 16:32 UTC, andrey-lepekhin commented on tests/functional/src/test_persons.py
> +    random_elem = random.randint(0, len(data_persons)-1)
А что если вместо хардкода в data_persons, ходить в эластик, доставать 10 персон и потом сравнивать ответ фастапи с ними?

2023-01-26 16:48 UTC, Polinavas95 commented on tests/functional/src/test_cache.py
> +pytestmark = pytest.mark.asyncio
да, это позволяет не использовать декораторы и работает в пределах файла. Если хочешь добавить еще какой-то декоратор, то помешаешь оба в список pytestmark = [1, 2]

2023-01-26 16:50 UTC, Polinavas95 commented on tests/functional/src/test_cache.py
> +        ('6e429cff-c8a2-4d17-8b12-6532a8a1ac9b', '6e429cff-c8a2-4d17-8b12-6532a8a1ac9b'),
ой, правда. одного параметра хватит
просто 3 теста в одном тесте прогоняются, чтобы проверить, что тест работает правильно
Например, у тебя тест проверяет деление. луяше проверить несколько пар чисел (5 / 2 = 2.5; 10 / 2 = 5)

2023-01-26 16:50 UTC, Polinavas95 commented on tests/functional/src/test_cache.py
> +    sleep(70)
о, второй вариант супер

2023-01-26 17:22 UTC, Polinavas95 commented on tests/functional/src/test_persons.py
> +    random_elem = random.randint(0, len(data_persons)-1)
Что-то попробовала сделать =)

2023-01-27 04:46 UTC, andrey-lepekhin commented on tests/functional/src/test_cache.py
> +pytestmark = pytest.mark.asyncio
Круто, спасибо!

2023-01-27 04:50 UTC, andrey-lepekhin commented on tests/functional/src/test_cache.py
> +        ('6e429cff-c8a2-4d17-8b12-6532a8a1ac9b', '6e429cff-c8a2-4d17-8b12-6532a8a1ac9b'),
Вот это для меня не очевидно, можешь сказать какая польза от множественных однотипных проверок? 

Типа если бы ты в одном случае делила на ноль и ловила ошибку, во втором просто делила, в третьем делила два отрицательных числа, -- тогда понятно. Но тут, если один id есть, а других не найдётся, проблема не в коде приложения будет, а в коде, который создает данные для тестов.

Да, вопрос можно переформулирвоать так: какую ошибку поймает этот тест с тремя айди, чего не поймает тест с одним айди?

2023-01-27 04:53 UTC, andrey-lepekhin commented on tests/functional/src/test_persons.py
> +    assert response.status == HTTPStatus.OK
HTTPStatus.OK -- моё увожение!

2023-01-27 04:55 UTC, andrey-lepekhin commented on tests/functional/src/test_persons.py
> +async def test_search_person_from_elastic(aiohttp_get, es_with_fresh_indexes) -> None:
Можешь рассказать какие ошибки ловит этот тест? Сходу не понимаю

2023-01-27 04:57 UTC, andrey-lepekhin commented on .env.example_test
> +PROJECT_NAME=movies
Так придётся поддерживать копию файла настроек актуальной. Лучше переписывать только то значение, которое тебе нужно.
Псмотри как сделано в docker-compose.tests.yml: туда можно добавить еще один файл энв в конец списка и внутри того файла указать только CACHE_EXPIRATION_IN_SECONDS

2023-01-27 08:59 UTC, Polinavas95 commented on .env.example_test
> +PROJECT_NAME=movies
точно! я буду копировать 2 файла в тесты и менять одно значение

2023-01-27 08:59 UTC, Polinavas95 commented on tests/functional/src/test_persons.py
> +async def test_search_person_from_elastic(aiohttp_get, es_with_fresh_indexes) -> None:
здесь получаем 10 случайных персон из эластика, получаем их имена и id. затем, с поммощью search по имени находим опять в эластике этих персон и сравниваем данные. может, этот тест лишний ?

2023-01-27 15:49 UTC, andrey-lepekhin commented on tests/docker-compose.yml
> +      - CACHE_EXPIRATION_IN_SECONDS=1
Похоже дублирвоание тут и в .env?

2023-01-27 15:49 UTC, andrey-lepekhin commented on tests/docker-compose.yml
> +      - CACHE_EXPIRATION_IN_SECONDS=1
Похоже дублирвоание тут и в .env?

2023-01-27 15:51 UTC, andrey-lepekhin commented on tests/functional/src/test_cache.py
> +    sleep(20)
Раз у нас асинк тесты, лучше использовать await asyncio.sleep(1)

2023-01-27 15:52 UTC, andrey-lepekhin commented on tests/functional/src/test_cache.py
> +    sleep(20)
Почему кстати 20, если кэш протухает за секунду?

2023-01-27 15:54 UTC, andrey-lepekhin commented on tests/functional/src/test_persons.py
> +    random_elem = random.randint(0, len(data_persons)-1)
А что тут получилось сделать? Кажется хардкод остался

2023-01-27 15:56 UTC, andrey-lepekhin commented on tests/functional/src/test_persons.py
> +async def test_search_person_from_elastic(aiohttp_get, es_with_fresh_indexes) -> None:
Мне тоже кажется что лишний, поэтому и задаю вопрос -- не понятно какую роль он выполняет

2023-01-27 15:57 UTC, andrey-lepekhin commented on tests/functional/src/test_search.py
> +    'status, endpoint, query_data, id_index',
Тут такие же вопросы, как к тестам выше 1) зачем одинаковые параметры 2) что тройной тест проверяет, что ординарный упустит

2023-01-27 15:59 UTC, andrey-lepekhin commented on tests/functional/src/test_cache.py
> +async def test_persons_cache_pass(person_id, aiohttp_get, es_async_client, es_with_fresh_indexes) -> None:
```suggestion
async def test_persons_cache(person_id, aiohttp_get, es_async_client, es_with_fresh_indexes) -> None:
```

2023-01-27 17:14 UTC, Polinavas95 commented on tests/functional/src/test_cache.py
> +        ('6e429cff-c8a2-4d17-8b12-6532a8a1ac9b', '6e429cff-c8a2-4d17-8b12-6532a8a1ac9b'),
Можно и 1 айди. Я просто хотела несколько проверок на одном тесте сделать =)

2023-01-27 17:16 UTC, Polinavas95 commented on tests/functional/src/test_persons.py
> +    random_elem = random.randint(0, len(data_persons)-1)
я оставила и этот тест, и без хардкода, чтобы было больше проверок. Но могу убрать =)

2023-01-27 17:17 UTC, Polinavas95 commented on tests/functional/src/test_persons.py
> +async def test_search_person_from_elastic(aiohttp_get, es_with_fresh_indexes) -> None:
Какой тест лучше оставить из этих двух?

2023-01-27 17:17 UTC, Polinavas95 commented on tests/docker-compose.yml
> +      - CACHE_EXPIRATION_IN_SECONDS=1
да, и эта переменная заменяет переменную в .env, чтобы не поддерживать отдельный файл .env.tests

2023-01-27 17:18 UTC, Polinavas95 commented on tests/functional/src/test_cache.py
> +    sleep(20)
просто от балды. Уменьшу до 5

2023-01-27 17:22 UTC, Polinavas95 commented on tests/functional/src/test_search.py
> +    'status, endpoint, query_data, id_index',
просто работу теста проверяю =) и тренируюсь на декораторе. Я уберу

2023-01-27 17:25 UTC, Polinavas95 commented on tests/functional/src/test_persons.py
> +async def test_search_person_from_elastic(aiohttp_get, es_with_fresh_indexes) -> None:
удалю тогда этот

2023-01-28 05:18 UTC, andrey-lepekhin commented on tests/docker-compose.yml
> +      - CACHE_EXPIRATION_IN_SECONDS=1
А тогда зачем вот этот файл, разве не для этого же?
![image](https://user-images.githubusercontent.com/35651221/215243622-7ca4a286-2601-4f5f-97e3-02b688375186.png)

2023-01-28 05:19 UTC, andrey-lepekhin commented on tests/docker-compose.yml
> +      - CACHE_EXPIRATION_IN_SECONDS=1
Плюс, это сервис эластика, тут эта переменная вообще никак не используется

2023-01-28 05:25 UTC, andrey-lepekhin commented on tests/functional/src/test_persons.py
> +    for person in random.sample(data['hits']['hits'], 10):
По умолчанию эластик возвращает 10 значений, а сэмпл тут берет 10 случайных значений из массива, который ему дают. То есть сэмпл тут ничего не делает.

2023-01-28 05:29 UTC, andrey-lepekhin requested changes
Почти всё готово!
Основной вопрос по .энв, остальное всё прекрасно

2023-01-28 05:57 UTC, Polinavas95 commented on tests/docker-compose.yml
> +      - CACHE_EXPIRATION_IN_SECONDS=1
а в докер десктопе почему-то показываося кэш в 300, вот я и поставила. тогда удалю 
поставлю в обоих компоузах в папке tests 
environment:
      - CACHE_EXPIRATION_IN_SECONDS=1
      потому что в makefile при щапуске тестов локально tests/docker-compose.tests.yml переписывает  env, а в последнем tests/docker-compose.yml

2023-01-28 06:29 UTC, andrey-lepekhin submitted a review, later dismissed

2023-01-28 06:37 UTC, andrey-lepekhin approved these changes

2023-01-28 06:37 UTC, merged