Vpg/07 functional test genre
andrey-lepekhin/Async_API_sprint_2 pull request #19
Opened 2023-01-27 18:48 UTC by Polinavas95

2023-01-28 17:45 UTC, andrey-lepekhin commented on tests/functional/src/test_persons.py
> -import random
А почему удаляешь?

2023-01-28 17:50 UTC, andrey-lepekhin requested changes
В целом все ок, я бы добавил кейс с запросом несуществующего жанра и все

2023-01-28 18:22 UTC, Polinavas95 commented on tests/functional/src/test_persons.py
> -import random
блин. Как так получилось. Я верну

2023-01-29 04:33 UTC, andrey-lepekhin commented on tests/functional/src/test_persons.py
> +    # Check that page[size] parameter changes number of shows per page
Тут нужно либо комменты и названия переменных поменять, либо сделать универсальный тест для всех эндпойнтов про это. Я за второй вариант, но это немного за рамками этой задачи, тут как хочешь.

2023-01-29 04:35 UTC, andrey-lepekhin requested changes
https://github.com/andrey-lepekhin/Async_API_sprint_2/pull/19/files#r1089864852

2023-01-29 05:59 UTC, Polinavas95 commented on tests/functional/src/test_persons.py
> +    # Check that page[size] parameter changes number of shows per page
переименую тест пока

2023-01-29 06:07 UTC, andrey-lepekhin approved these changes

2023-01-29 06:09 UTC, merged