пункт 3
andrey-lepekhin/Async_API_sprint_2 pull request #33
Opened 2023-01-31 12:22 UTC by Polinavas95

Сделала плагин для систематизации фикстур и перенесла туда пару тестов для эластика

2023-01-31 13:49 UTC, andrey-lepekhin commented on tests/conftest.py
>  def make_indexes_snapshot(make_es_repo, es_client):
Вот этот тоже по идее нужно вынести в файл с эластиком

2023-01-31 13:50 UTC, andrey-lepekhin commented on tests/conftest.py
>      return inner
А датакласс HTTPResponse и всё про http можно вынести в файл фикстур типа async_http

2023-01-31 13:50 UTC, andrey-lepekhin requested changes
Небольшие правки

2023-01-31 14:09 UTC, Polinavas95 commented on tests/conftest.py
>      return inner
Давай! Я сделала для примера, чтобы работало :) сделаю файл для http

2023-01-31 14:09 UTC, Polinavas95 commented on tests/conftest.py
>  def make_indexes_snapshot(make_es_repo, es_client):
Без проблем

2023-02-01 17:41 UTC, andrey-lepekhin approved these changes

2023-02-01 17:42 UTC, merged